version: '3.8'

services:
  db:
    build: ./db
    container_name: expense_db
    restart: always
    ports:
      - "3307:3306"          
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: expense_db
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass

  web:
    build: ./app            
    container_name: expense_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mariadb+mariadbconnector://user:userpass@db:3306/expense_db"
    depends_on:
      - db

volumes:
  db_data: