version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: expense_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: expense_db
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass
    ports:
      - "3307:3306"   # Changed host port to 3307
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: expense_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mariadb+mariadbconnector://user:userpass@db:3306/expense_db"
    depends_on:
      - db

volumes:
  db_data:
