CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  amount DOUBLE NOT NULL,
  category VARCHAR(255) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
);